# Generated by Django 4.0.2 on 2024-03-08 08:21

import core.security.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alterna',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Imagen Alterna'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='product',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Exclusivo'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alterna',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Imagen Alterna'),
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publico'),
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='product',
            name='soldout',
            field=models.BooleanField(default=False, verbose_name='Agotado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=13, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='identification_type',
            field=models.CharField(choices=[('05', 'CEDULA'), ('04', 'NIT'), ('06', 'PASAPORTE'), ('07', 'VENTA A CONSUMIDOR FINAL*'), ('08', 'IDENTIFICACION DELEXTERIOR*')], default='05', max_length=30, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnotedetail',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ctascollect',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ctascollect',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debtspay',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debtspay',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='paymentsdebtspay',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='end_credit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de plazo de credito'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de registro'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='end_credit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha limite de credito'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('01', 'SIN UTILIZACION DEL SISTEMA FINANCIERO'), ('15', 'COMPENSACIÓN DE DEUDAS'), ('16', 'TARJETA DÉBITO'), ('17', 'DINERO ELECTRÓNICO'), ('18', 'TARJETA PREPAGO'), ('20', 'OTROS CON UTILIZACION DEL SISTEMA FINANCIERO'), ('21', 'ENDOSO DE TÍTULOS')], default='20', max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='vouchererrors',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vouchererrors',
            name='datetime_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
