name: publish

on:
  push:
    branches: ["main"]

jobs:
  creta-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Register
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/Jeffer-UAO/django-docker-prueba-v1:latest
          docker push ghcr.io/Jeffer-UAO/django-docker-prueba-v1:latest

  deploy:
    needs: creta-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt update && sudo apt install -y sshpass

      - name: SSH into Server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ssheasy@143.244.186.207 -p 22010 'mkdir -p ~/.ssh && echo "$(cat <<EOF
          cd /home/ssheasy/django-docker
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}
          docker pull ghcr.io/Jeffer-UAO/django-docker-prueba-v1:latest
          docker stop django-docker-prueba-v1
          docker rm django-docker-prueba-v1
          docker run -d \
            --name django-docker-prueba-v1 \
            -p 8080:8080 \
            -v $(pwd):/app \
            -w /app \
            --restart always \
            --env-file .env \
            ghcr.io/Jeffer-UAO/django-docker-prueba-v1:latest
          EOF
          )'
